services:
  envoy:
    depends_on:
    - echo
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/envoyproxy/envoy
        APP_VERSION: 712b73658357f97bb7b53b33b497258b5a83b1ac
        BACKEND: echo
      context: ./images/envoy
    x-props:
      role: transducer
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: 9c0f3d0d6c3859a13c3f76e8f934bc30486a33fe
      context: ./images/aiohttp
    volumes:
    - /tmp/aiohttp:/tmp
    x-props:
      is-traced: true
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 4a9cd1fccf8e79eda2132d65166af6e87e4f5fe9
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: d131b4e1be4fc45e9f092cff90d7c87baa251e2b
        CONFIG_FILE: server.conf
      context: ./images/apache_httpd
    volumes:
    - /tmp/apache_httpd:/tmp
    x-props:
      is-traced: true
      role: origin
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: 4a9cd1fccf8e79eda2132d65166af6e87e4f5fe9
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: d131b4e1be4fc45e9f092cff90d7c87baa251e2b
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/apache_httpd
    depends_on:
    - echo
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 1afe41491f0e56ec0a776db5ff84607f87ce6640
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: addbe0b3fbb29caf417832706966a33b85d07507
        BACKEND: echo
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    depends_on:
    - echo
    x-props:
      role: transducer
  busybox_httpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.busybox.net/busybox/
        APP_VERSION: 14f57f5357cb674b88e7cdaff6267bf9d84c6b80
        BACKEND: echo
        CONFIG_FILE: httpd_proxy.conf
      context: ./images/busybox_httpd
    depends_on:
    - echo
    x-props:
      role: transducer
  cheroot:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/cherrypy/cheroot
        APP_VERSION: a9c1fe465a8642a16cb290d9667d4c624d80b306
      context: ./images/cheroot
    volumes:
    - /tmp/cheroot:/tmp
    x-props:
      is-traced: true
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: b85768c1f34f8b7ff60dfe0e2938b35b50e2610b
      context: ./images/cpp_httplib
    x-props:
      role: origin
  cpython_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/python/cpython
        APP_VERSION: 2a66dd33dfc0b845042da9bb54aaa4e890733f54
      context: ./images/cpython_stdlib
    x-props:
      role: origin
  dart_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/dart-lang/sdk
        APP_VERSION: 354c64f52f3813874f04cae26919cae8d7651bb8
      context: ./images/dart_stdlib
    x-props:
      role: origin
  echo:
    build:
      context: ./images/echo
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 4316ca1adbaa00341d142d8ae571932294511a96
      context: ./images/eclipse_grizzly
    x-props:
      port: 8080
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.0.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: 818bd0ee98bfe526b370617215d9a2e4a5f5edb2
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: ce283fb97c2e0c4801e68fd6c362a81a8a5c74b5
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: 06b191e11f6f78b19e5c5a43b3d0c461226c7084
      context: ./images/go_stdlib
    x-props:
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: 06b191e11f6f78b19e5c5a43b3d0c461226c7084
        BACKEND: echo
      context: ./images/go_stdlib
    depends_on:
    - echo
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: bacbf8aa5152b94e44aa5d2a94aeaf0318a85248
      context: ./images/gunicorn
    volumes:
    - /tmp/gunicorn:/tmp
    x-props:
      is-traced: true
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: ebcd7f47d89525fd93252a8ba99ca732abda0fdb
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8d0513f1a7a111f2597d643b073935a8afaf9e5
      context: ./images/h2o
    volumes:
    - /tmp/h2o:/tmp
    x-props:
      is-traced: true
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: ebcd7f47d89525fd93252a8ba99ca732abda0fdb
        BACKEND: echo
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8d0513f1a7a111f2597d643b073935a8afaf9e5
      context: ./images/h2o
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 29b6d8af16884bb8f0b5cd83a3752980df8548d0
        BACKEND: echo
        CONFIG_FILE: haproxy.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 29b6d8af16884bb8f0b5cd83a3752980df8548d0
        CONFIG_FILE: haproxy-fcgi.conf
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_invalid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 29b6d8af16884bb8f0b5cd83a3752980df8548d0
        BACKEND: echo
        CONFIG_FILE: haproxy-invalid.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: 30f2961e89eb306780d856e6e2c1ee10ffbbafd2
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 84d06b8cf47798d2df7722273341e720ec0ea102
      context: ./images/hypercorn
    volumes:
    - /tmp/hypercorn:/tmp
    x-props:
      is-traced: true
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: a0888a018912320d6df73763544595a6145b84ed
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 9a6a799e7002aae09d5e7cb244bdb913eed75a04
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: 5e40455beae130dd0dd239a7a2447b88496c3be8
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: abc01220333650b959d87206c8e3804adddd7b7b
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 2bf81d4105c68ea1bef6c146fd7911f7ebbb024d
        CONFIG_FILE: server.conf
      context: ./images/lighttpd
    volumes:
    - /tmp/lighttpd:/tmp
    x-props:
      is-traced: true
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: 2bf81d4105c68ea1bef6c146fd7911f7ebbb024d
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/lighttpd
    depends_on:
    - echo
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 553aeeef773b13f54eca9853f7b26839f0dae680
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    volumes:
    - /tmp/mongoose:/tmp
    x-props:
      is-traced: true
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: '4.1'
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: 07365430def337d6b39b11c2971975cf7c9c4111
      context: ./images/netty
    x-props:
      role: origin
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 930caed3bfc84e43bf4bd034150c17604dc5dc73
        CONFIG_FILE: nginx.conf
      context: ./images/nginx
    volumes:
    - /tmp/nginx:/tmp
    x-props:
      is-traced: true
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: 930caed3bfc84e43bf4bd034150c17604dc5dc73
        BACKEND: echo
        CONFIG_FILE: nginx-proxy.conf
      context: ./images/nginx
    depends_on:
    - echo
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: 60e9c6f441c6e43b7977eb0f9f669d0c3900cabf
        PARSER_BRANCH: main
        PARSER_REPO: https://github.com/nodejs/llhttp
        PARSER_VERSION: f9d9465ffa61d59e2c78c8c1333528edc152f04a
      context: ./images/node_stdlib
    x-props:
      role: origin
      version_frozen: true
  openbsd_httpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/kenballus/obhttpd-linux
        APP_VERSION: 26af49aefde6a130ae97b8e233b93915db78d6b4
        OPENBSD_SRC_BRANCH: master
        OPENBSD_SRC_REPO: https://github.com/openbsd/src
        OPENBSD_SRC_VERSION: b03657559450670f90f66df122081d038341e13d
      context: ./images/openbsd_httpd
    x-props:
      role: origin
  openlitespeed:
    build:
      args:
        APP_BRANCH: v1.8.2
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.2
        CONFIG_FILE: server_config.conf
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
      version_frozen: true
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: v1.8.2
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.2
        BACKEND: echo
        CONFIG_FILE: proxy_config.conf
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    depends_on:
    - echo
    x-props:
      role: transducer
      version_frozen: true
  openwrt_uhttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.openwrt.org/project/uhttpd.git
        APP_VERSION: 34a8a74dbdec3c0de38abc1b08f6a73c51263792
        LIBUBOX_BRANCH: master
        LIBUBOX_REPO: https://git.openwrt.org/project/libubox.git
        LIBUBOX_VERSION: 3868f47c8f6c6570e62a3cdf8a7f26ffb1a67e6a
        LIBUBUS_BRANCH: master
        LIBUBUS_REPO: https://git.openwrt.org/project/ubus.git
        LIBUBUS_VERSION: 252a9b0c1774790fb9c25735d5a09c27dba895db
        UCODE_BRANCH: master
        UCODE_REPO: https://github.com/jow-/ucode
        UCODE_VERSION: ef7033878f878c9a4c51ab73353db7b93a4f99e3
        USTREAM_SSL_BRANCH: master
        USTREAM_SSL_REPO: https://git.openwrt.org/project/ustream-ssl.git
        USTREAM_SSL_VERSION: 99bd3d2b167ccdffb6de072d02c380cb37b23e33
      context: ./images/openwrt_uhttpd
    volumes:
    - /tmp/openwrt_uhttpd:/tmp
    x-props:
      is-traced: true
      role: origin
      timeout: 0.2
  php_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/php/php-src
        APP_VERSION: 26244c7dcd2ed91a66e3f75dad7c837308ccbc09
      context: ./images/php_stdlib
    x-props:
      role: origin
  phusion_passenger:
    build:
      args:
        APP_BRANCH: stable-6.0
        APP_REPO: https://github.com/phusion/passenger
        APP_VERSION: c7599c49ef2d757c877045564f26156bb36dc4e5
      context: ./images/phusion_passenger
    x-props:
      role: origin
  pingora:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/cloudflare/pingora
        APP_VERSION: a37224b50061d3a2e76ef1fbd87d426c7b904d51
        BACKEND: echo
      context: ./images/pingora
    depends_on:
    - echo
    x-props:
      role: transducer
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: 181117673a00addf61531541f5b6c8bd9799ae86
        BACKEND: echo
      context: ./images/pound
    depends_on:
    - echo
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: db96687509548e54f28ff3ebcb156bf4c70d4e4d
      context: ./images/protocol_http1
    x-props:
      role: origin
      timeout: 0.2
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: 4d7f4e77bde20df51bfad4d8a1f290273c6b1fe7
      context: ./images/puma
    x-props:
      role: origin
  servicetalk:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apple/servicetalk
        APP_VERSION: 6fc79877e278769c7c1fe758c2e7f04ce9c2d83b
      context: ./images/servicetalk
    x-props:
      role: origin
  spring_cloud_gateway:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/spring-cloud/spring-cloud-gateway
        APP_VERSION: cf916f35e55bb591b8544e77455bb39c94b4b2a5
        BACKEND: echo
      context: ./images/spring_cloud_gateway
    depends_on:
    - echo
    x-props:
      port: 8080
      role: transducer
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: 75c97d271047f1e6041d49a9a96e3aca2de4cc60
        BACKEND: echo
      context: ./images/squid
    depends_on:
    - echo
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: 0a39ba8b6ac0beb48a3244098cfa72ce1f59f215
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: f5b49aba6752db1b453a1f1fdfdc4f7e01b29598
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: 6ae61c6af88d2a8341922ccd0de98926e8349543
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/encode/uvicorn
        APP_VERSION: 7983c1ae9c2276b94cd85217f7aa58bb248847c4
      context: ./images/uvicorn
    volumes:
    - /tmp/uvicorn:/tmp
    x-props:
      is-traced: true
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: e3aa6133952b898c07098c918585778ee4b4365e
        BACKEND: echo
      context: ./images/varnish
    depends_on:
    - echo
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: fc592e804a1aed87654c1ad21337dad86582c71f
      context: ./images/waitress
    volumes:
    - /tmp/waitress:/tmp
    x-props:
      is-traced: true
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: 307f24c0e9624e56fdbe8ebbe6df03ee25e9e57b
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 77b03460154eeb14decb40126580fc66f58549b0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: 1370f52bb0e63575ebaf11b0700751f792cd0e96
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 77b03460154eeb14decb40126580fc66f58549b0
        BACKEND: echo
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: 1370f52bb0e63575ebaf11b0700751f792cd0e96
      context: ./images/yahns
    depends_on:
    - echo
    x-props:
      role: transducer
