services:
  aiohttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/aio-libs/aiohttp
        APP_VERSION: 0130213423d8d055ece27c36a4dcc96e524cbc1c
      context: ./images/aiohttp
    volumes:
    - /tmp/aiohttp:/tmp
    x-props:
      is-traced: true
      role: origin
  apache_httpd:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: cae775f2f61b2bc3e656b1149b60cf96463dff21
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: d131b4e1be4fc45e9f092cff90d7c87baa251e2b
        CONFIG_FILE: server.conf
      context: ./images/apache_httpd
    volumes:
    - /tmp/apache_httpd:/tmp
    x-props:
      is-traced: true
      role: origin
  apache_httpd_proxy:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/apache/httpd
        APP_VERSION: cae775f2f61b2bc3e656b1149b60cf96463dff21
        APR_BRANCH: trunk
        APR_REPO: https://github.com/apache/apr
        APR_VERSION: d131b4e1be4fc45e9f092cff90d7c87baa251e2b
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/apache_httpd
    depends_on:
    - echo
    x-props:
      role: transducer
  apache_tomcat:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apache/tomcat
        APP_VERSION: 38a1b6ef20ff26a9938242fde0426d48025e6d51
      context: ./images/apache_tomcat
    x-props:
      role: origin
  apache_traffic_server:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/apache/trafficserver
        APP_VERSION: b65a8418d73afe49b514f14180ba592f4697d23b
        BACKEND: echo
        CACHE_CONFIG: cache.config
        RECORDS_YAML: records.yaml
        REMAP_CONFIG: remap.config
      context: ./images/apache_traffic_server
    depends_on:
    - echo
    x-props:
      role: transducer
  cheroot:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/cherrypy/cheroot
        APP_VERSION: a9c1fe465a8642a16cb290d9667d4c624d80b306
      context: ./images/cheroot
    volumes:
    - /tmp/cheroot:/tmp
    x-props:
      is-traced: true
      role: origin
  cpp_httplib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/yhirose/cpp-httplib
        APP_VERSION: 258992a160e306b6907c74abed448e487b60f74c
      context: ./images/cpp_httplib
    x-props:
      role: origin
  cpython_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/python/cpython
        APP_VERSION: 208b0fb645c0e14b0826c0014e74a0b70c58c9d6
      context: ./images/cpython_stdlib
    x-props:
      role: origin
  dart_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/dart-lang/sdk
        APP_VERSION: e30f60791a24e8e4f51392d8c24dc1564934ab53
      context: ./images/dart_stdlib
    x-props:
      role: origin
  echo:
    build:
      context: ./images/echo
  eclipse_grizzly:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/eclipse-ee4j/grizzly
        APP_VERSION: 4316ca1adbaa00341d142d8ae571932294511a96
      context: ./images/eclipse_grizzly
    x-props:
      port: 8080
      role: origin
  eclipse_jetty:
    build:
      args:
        APP_BRANCH: jetty-12.0.x
        APP_REPO: https://github.com/eclipse/jetty.project
        APP_VERSION: d650efeec4f10e584a56c755c71dc28c51ba0672
      context: ./images/eclipse_jetty
    x-props:
      role: origin
  fasthttp:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/valyala/fasthttp
        APP_VERSION: 7b74fc98457ce08b2d8a445660c1f9e55eca782f
      context: ./images/fasthttp
    x-props:
      role: origin
  go_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: app.go
        APP_VERSION: be297ba9b32a56630a655393142bb33bafd297df
      context: ./images/go_stdlib
    x-props:
      role: origin
  go_stdlib_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/golang/go
        APP_SOURCE: proxy.go
        APP_VERSION: be297ba9b32a56630a655393142bb33bafd297df
        BACKEND: echo
      context: ./images/go_stdlib
    depends_on:
    - echo
    x-props:
      role: transducer
  gunicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/benoitc/gunicorn
        APP_VERSION: bacbf8aa5152b94e44aa5d2a94aeaf0318a85248
      context: ./images/gunicorn
    volumes:
    - /tmp/gunicorn:/tmp
    x-props:
      is-traced: true
      role: origin
  h2o:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: d750b56aa929d55d9d18b9d2a7adea53ec898114
        CONFIG_FILE: h2o.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8d0513f1a7a111f2597d643b073935a8afaf9e5
      context: ./images/h2o
    volumes:
    - /tmp/h2o:/tmp
    x-props:
      is-traced: true
      role: origin
  h2o_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/h2o/h2o.git
        APP_VERSION: d750b56aa929d55d9d18b9d2a7adea53ec898114
        BACKEND: echo
        CONFIG_FILE: h2o-proxy.conf
        PARSER_BRANCH: master
        PARSER_REPO: https://github.com/h2o/picohttpparser
        PARSER_VERSION: f8d0513f1a7a111f2597d643b073935a8afaf9e5
      context: ./images/h2o
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 7885a3b3e159323ae3e67f7bbfb4567f2031dc9e
        BACKEND: echo
        CONFIG_FILE: haproxy.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  haproxy_fcgi:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 7885a3b3e159323ae3e67f7bbfb4567f2031dc9e
        CONFIG_FILE: haproxy-fcgi.conf
      context: ./images/haproxy
    x-props:
      role: origin
  haproxy_invalid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/haproxy/haproxy
        APP_VERSION: 7885a3b3e159323ae3e67f7bbfb4567f2031dc9e
        BACKEND: echo
        CONFIG_FILE: haproxy-invalid.conf
      context: ./images/haproxy
    depends_on:
    - echo
    x-props:
      role: transducer
  hyper:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/hyperium/hyper
        APP_VERSION: 12717d16594debd8f2b1e3e169cc9b4700ee25b3
      context: ./images/hyper
    x-props:
      role: origin
  hypercorn:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/pgjones/hypercorn
        APP_VERSION: 84d06b8cf47798d2df7722273341e720ec0ea102
      context: ./images/hypercorn
    volumes:
    - /tmp/hypercorn:/tmp
    x-props:
      is-traced: true
      role: origin
  ktor:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/ktorio/ktor
        APP_VERSION: 6d26bc9c589e10cbbc5fb1e4787c8b09c329f9fc
      context: ./images/ktor
    x-props:
      role: origin
  libevent:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/libevent/libevent
        APP_VERSION: 9a6a799e7002aae09d5e7cb244bdb913eed75a04
      context: ./images/libevent
    x-props:
      role: origin
  libmicrohttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.gnunet.org/libmicrohttpd.git
        APP_VERSION: 5e40455beae130dd0dd239a7a2447b88496c3be8
      context: ./images/libmicrohttpd
    x-props:
      role: origin
  libsoup:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://gitlab.gnome.org/GNOME/libsoup.git
        APP_VERSION: 8b46a93bc1cbadb22dcdbb6844d9616723376535
      context: ./images/libsoup
    x-props:
      role: origin
  lighttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: b9080026da0028844e19d34b2d1bef1ddf1ee74a
        CONFIG_FILE: server.conf
      context: ./images/lighttpd
    volumes:
    - /tmp/lighttpd:/tmp
    x-props:
      is-traced: true
      role: origin
  lighttpd_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/lighttpd/lighttpd1.4
        APP_VERSION: b9080026da0028844e19d34b2d1bef1ddf1ee74a
        BACKEND: echo
        CONFIG_FILE: proxy.conf
      context: ./images/lighttpd
    depends_on:
    - echo
    x-props:
      role: transducer
  mongoose:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/cesanta/mongoose
        APP_VERSION: 0a4f322d49d4e9520d5726cbed967e111137c9ed
        SERVER_SOURCE: main.c
      context: ./images/mongoose
    volumes:
    - /tmp/mongoose:/tmp
    x-props:
      is-traced: true
      role: origin
  netty:
    build:
      args:
        APP_BRANCH: '4.1'
        APP_REPO: https://github.com/netty/netty
        APP_VERSION: 2eb7fcef56ae82ab5ca5e1c9e03901bf94df204b
      context: ./images/netty
    x-props:
      role: origin
  nginx:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: e28ef42b97d5352e514f019cd3b9a6c07a87c580
        CONFIG_FILE: nginx.conf
      context: ./images/nginx
    volumes:
    - /tmp/nginx:/tmp
    x-props:
      is-traced: true
      role: origin
  nginx_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/nginx/nginx
        APP_VERSION: e28ef42b97d5352e514f019cd3b9a6c07a87c580
        BACKEND: echo
        CONFIG_FILE: nginx-proxy.conf
      context: ./images/nginx
    depends_on:
    - echo
    x-props:
      role: transducer
  node_stdlib:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/nodejs/node
        APP_VERSION: 60e9c6f441c6e43b7977eb0f9f669d0c3900cabf
        PARSER_BRANCH: main
        PARSER_REPO: https://github.com/nodejs/llhttp
        PARSER_VERSION: f9d9465ffa61d59e2c78c8c1333528edc152f04a
      context: ./images/node_stdlib
    x-props:
      role: origin
      version_frozen: true
  openlitespeed:
    build:
      args:
        APP_BRANCH: v1.8.2
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.2
        CONFIG_FILE: server_config.conf
        VHOST_CONFIG_FILE: server_vhost.conf
      context: ./images/openlitespeed
    x-props:
      role: origin
      version_frozen: true
  openlitespeed_proxy:
    build:
      args:
        APP_BRANCH: v1.8.2
        APP_REPO: https://github.com/litespeedtech/openlitespeed
        APP_VERSION: 1.8.2
        BACKEND: echo
        CONFIG_FILE: proxy_config.conf
        VHOST_CONFIG_FILE: proxy_vhost.conf
      context: ./images/openlitespeed
    depends_on:
    - echo
    x-props:
      role: transducer
      version_frozen: true
  openwrt_uhttpd:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://git.openwrt.org/project/uhttpd.git
        APP_VERSION: 34a8a74dbdec3c0de38abc1b08f6a73c51263792
        LIBUBOX_BRANCH: master
        LIBUBOX_REPO: https://git.openwrt.org/project/libubox.git
        LIBUBOX_VERSION: eb9bcb64185ac155c02cc1a604692c4b00368324
        LIBUBUS_BRANCH: master
        LIBUBUS_REPO: https://git.openwrt.org/project/ubus.git
        LIBUBUS_VERSION: 252a9b0c1774790fb9c25735d5a09c27dba895db
        UCODE_BRANCH: master
        UCODE_REPO: https://github.com/jow-/ucode
        UCODE_VERSION: 3f7035c4b294a41609b8562ace08a89b40225492
        USTREAM_SSL_BRANCH: master
        USTREAM_SSL_REPO: https://git.openwrt.org/project/ustream-ssl.git
        USTREAM_SSL_VERSION: 99bd3d2b167ccdffb6de072d02c380cb37b23e33
      context: ./images/openwrt_uhttpd
    volumes:
    - /tmp/openwrt_uhttpd:/tmp
    x-props:
      is-traced: true
      role: origin
      timeout: 0.2
  php_stdlib:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/php/php-src
        APP_VERSION: 2b80b2e5ecb2c4e769790d43f13b977a18cb61ac
      context: ./images/php_stdlib
    x-props:
      role: origin
  phusion_passenger:
    build:
      args:
        APP_BRANCH: stable-6.0
        APP_REPO: https://github.com/phusion/passenger
        APP_VERSION: 2a6c035162f4a894426f9efc13c158ef47a858e2
      context: ./images/phusion_passenger
    x-props:
      role: origin
  pingora:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/cloudflare/pingora
        APP_VERSION: e309436319ed5cbc3aaf53221070a1fd070b8bcf
        BACKEND: echo
      context: ./images/pingora
    depends_on:
    - echo
    x-props:
      role: transducer
  pound:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/graygnuorg/pound
        APP_VERSION: 181117673a00addf61531541f5b6c8bd9799ae86
        BACKEND: echo
      context: ./images/pound
    depends_on:
    - echo
    x-props:
      role: transducer
  protocol_http1:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/socketry/protocol-http1
        APP_VERSION: db96687509548e54f28ff3ebcb156bf4c70d4e4d
      context: ./images/protocol_http1
    x-props:
      role: origin
      timeout: 0.2
  puma:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/puma/puma
        APP_VERSION: 2c9aafef0ea42058bf3bb03f53805680fffecc60
      context: ./images/puma
    x-props:
      role: origin
  servicetalk:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/apple/servicetalk
        APP_VERSION: 8f72e01cc2393c5d45ffa5d760ed09c725de83e3
      context: ./images/servicetalk
    x-props:
      role: origin
  spring_cloud_gateway:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/spring-cloud/spring-cloud-gateway
        APP_VERSION: 62a13c31e30b7be414576763ceba8108c3cfeb7e
        BACKEND: echo
      context: ./images/spring_cloud_gateway
    depends_on:
    - echo
    x-props:
      port: 8080
      role: transducer
  squid:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/squid-cache/squid
        APP_VERSION: 9685cb72268c5f9df073b9cea3ea6066863288c8
        BACKEND: echo
      context: ./images/squid
    depends_on:
    - echo
    x-props:
      role: transducer
  tornado:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/tornadoweb/tornado
        APP_VERSION: f62afc31bc8908a2c9d0c21f74bc1447781e4782
      context: ./images/tornado
    x-props:
      role: origin
  twisted:
    build:
      args:
        APP_BRANCH: trunk
        APP_REPO: https://github.com/twisted/twisted
        APP_VERSION: 58421972a047eaa917d771f03e31062ed99eb5bc
      context: ./images/twisted
    x-props:
      role: origin
  undertow:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/undertow-io/undertow
        APP_VERSION: 84c2d6ca66c7a4882f4de212a621c0682bbe8635
      context: ./images/undertow
    x-props:
      role: origin
  uvicorn:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/encode/uvicorn
        APP_VERSION: bfa754e21e2cc1d5b0d7cabf24933a6c3afc315e
      context: ./images/uvicorn
    volumes:
    - /tmp/uvicorn:/tmp
    x-props:
      is-traced: true
      role: origin
  varnish:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/varnishcache/varnish-cache
        APP_VERSION: a1c26cab87670d4b6b2deea52505f4dc6626b9c6
        BACKEND: echo
      context: ./images/varnish
    depends_on:
    - echo
    x-props:
      role: transducer
  waitress:
    build:
      args:
        APP_BRANCH: main
        APP_REPO: https://github.com/Pylons/waitress
        APP_VERSION: fc592e804a1aed87654c1ad21337dad86582c71f
      context: ./images/waitress
    volumes:
    - /tmp/waitress:/tmp
    x-props:
      is-traced: true
      role: origin
  webrick:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://github.com/ruby/webrick
        APP_VERSION: 307f24c0e9624e56fdbe8ebbe6df03ee25e9e57b
      context: ./images/webrick
    x-props:
      role: origin
  yahns:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 77b03460154eeb14decb40126580fc66f58549b0
        CONFIG_FILE: server.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: 1370f52bb0e63575ebaf11b0700751f792cd0e96
      context: ./images/yahns
    x-props:
      role: origin
  yahns_proxy:
    build:
      args:
        APP_BRANCH: master
        APP_REPO: https://yhbt.net/yahns.git
        APP_VERSION: 77b03460154eeb14decb40126580fc66f58549b0
        BACKEND: echo
        CONFIG_FILE: proxy.ru
        PARSER_BRANCH: master
        PARSER_REPO: https://yhbt.net/unicorn.git
        PARSER_VERSION: 1370f52bb0e63575ebaf11b0700751f792cd0e96
      context: ./images/yahns
    depends_on:
    - echo
    x-props:
      role: transducer
