http:
  routers:
    router0:
      entryPoints: [web]
      service: the-service
      rule: Path(`/`)

  services:
    the-service:
      loadBalancer:
        servers:
        - url: "http://PROXY_BACKEND_PLACEHOLDER:80"
        passHostHeader: true
